language: ruby

rvm:
  - "1.8.7"
  - "1.9.3"

before_install:
  - echo "BEFORE INSTALL START"
  - sudo apt-get install -qq libaugeas-dev
  - gem install bundler
  - echo "BEFORE INSTALL END"

script:
  - bundle exec rake spec

env:
  - PUPPET_VERSION="2.7"
  - PUPPET_VERSION="3.0"

branches:
  except:
    - master
    - gh-pages
    - /^talk.*$/
    - /^vagrant.*$/
